plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
}

loom {
    runs {
        fabricClient {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('../runs/client')
        }
        fabricServer {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('../runs/server')
        }
    }
}