plugins {
    // see https://fabricmc.net/develop/ for new versions
    id 'fabric-loom' version '1.7-SNAPSHOT' apply false
    // see https://projects.neoforged.net/neoforged/moddevgradle for new versions
    id 'net.neoforged.moddev' version '0.1.110' apply false
    id "io.github.pacifistmc.forgix" version "1.2.9"
}

forgix {
    group = group
    mergedJarName = "${mod_name}-${version}.jar"
    outputDir = "merged/build/libs"
    // removeDuplicate "com.legobmw99.BetterThanMending.core"
    fabric {
        jarLocation = "build/libs/${mod_name}-fabric-${version}.jar"
    }
    neoforge {
        jarLocation = "build/libs/${mod_name}-neoforge-${version}.jar"
    }
    forge {
        jarLocation = "build/libs/${mod_name}-forge-${version}.jar"
    }
}