plugins {
    // see https://fabricmc.net/develop/ for new versions
    id 'fabric-loom' version '1.7-SNAPSHOT' apply false
    // see https://projects.neoforged.net/neoforged/moddevgradle for new versions
    id 'net.neoforged.moddev' version '0.1.110' apply false
    // build a single jar with multiple loaders supported
    id "com.hypherionmc.modutils.modfusioner" version "1.0.+"
}

fusioner {
    group = project.group
    mergedJarName = "${mod_name}-${version}.jar"
    outputDirectory = "merged/build/libs"
    relocateDuplicate "com.legobmw99.BetterThanMending.core"

    fabric {
        projectName = "fabric"
        inputTaskName = "jar"
    }
    neoforge {
        projectName = "neoforge"
        inputTaskName = "jar"
    }
    forge {
        projectName = "forge"
        inputTaskName = "jar"
    }
}

tasks.register('build') { t ->
   group = "build"
   t.dependsOn(subprojects*.tasks*.findByName('build').minus(null))
   t.finalizedBy(fusejars)
}

tasks.register('clean') { t ->
   group = "build"
   t.dependsOn(subprojects*.tasks*.findByName('clean').minus(null))

   def mergedFolder = file("merged")
   if (mergedFolder.exists()) {
       delete(mergedFolder)
   }
   def buildFolder = file("build")
   if (buildFolder.exists()) {
       delete(buildFolder)
   }
}