# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.
# Project
version=2.2.6
group=com.legobmw99.BetterThanMending
java_version=21
# Common
minecraft_version=1.21.11
mod_name=BetterThanMending
mod_author=Legobmw99
mod_id=betterthanmending
license=GPL-3.0
credits=
description=A mod to improve the mending behavior in vanilla Minecraft.
minecraft_version_range=[1.21.10,)
# Fabric
# https://fabricmc.net/develop/
fabric_version=0.136.0+1.21.10
fabric_loader_version=0.17.3
# Forge
# https://files.minecraftforge.net/net/minecraftforge/forge/
forge_version=60.0.5
forge_loader_version_range=[60,)
forge_version_range=[60,)
# NeoForge
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=21.10.20-beta
neoforge_loader_version_range=[4,)
# This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
# https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.10-20251010.172816
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.10
parchment_version=2025.10.12

# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false