plugins {
    id 'idea'
    id 'multiloader-loader'
    id 'net.minecraftforge.gradle' version '[6.0.36,6.2)'
}
base {
    archivesName = "${mod_name}-forge"
}

minecraft {
    mappings channel: 'official', version: minecraft_version

    copyIdeResources = true //Calls processResources when in dev

    reobf = false // Forge 1.20.6+ uses official mappings at runtime, so we shouldn't reobf from official to SRG

    runs {
        client {
            workingDirectory project.file('../runs/client')
            ideaModule "${rootProject.name}.${project.name}.main"
            property 'eventbus.api.strictRuntimeChecks', 'true'
            taskName 'Client'
            mods {
                modClientRun {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file('../runs/server')
            ideaModule "${rootProject.name}.${project.name}.main"
            property 'eventbus.api.strictRuntimeChecks', 'true'
            taskName 'Server'
            mods {
                modServerRun {
                    source sourceSets.main
                }
            }
        }
    }
}

sourceSets.main.resources.srcDir 'src/generated/resources'

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
    // Forge's hack fix
    implementation('net.sf.jopt-simple:jopt-simple:5.0.4') { version { strictly '5.0.4' } }
    annotationProcessor 'net.minecraftforge:eventbus-validator:7.0-beta.9'
}

sourceSets.each {
    def dir = layout.buildDirectory.dir("sourcesSets/$it.name")
    it.output.resourcesDir = dir
    it.java.destinationDirectory = dir
}