name: BTM Fabric build

on:
  push:
    branches: [ fabric ]
  pull_request:
    branches: [ fabric ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: fabric
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
        key: ${{ runner.os }}-gradle-fabric-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-fabric-
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Stop gradle daemon
      run: ./gradlew --stop
    - uses: actions/upload-artifact@v2
      with:
        name: BTM jar
        path: build/libs/*.jar
